### PR TITLE
Adding Content-Type to all output formats (#336)

### PR DESCRIPTION
**Pull request by l4yton**
# Description
The JSON and CSV output file formats now include the `Content-Type` in the output. I think this is useful for everyone that is using ffuf to automate their recon and can now use the content-type to determine if a specific endpoint may be interesting or not.

Fixes: #336 

## Additonally

- [X] If this is the first time you are contributing to ffuf, add your name to `CONTRIBUTORS.md`. 
The file should be alphabetically ordered.
- [X] Add a short description of the fix to `CHANGELOG.md`

### CODE REVIEW

**Comment by joohoi** [comment]
I think it's a good feature. Though I'd like to keep consistent throughout  the different output file type options. Do you think it could be feasible to add these to the HTML and MD output formats as well?

**Comment by l4yton** [comment]
Done, it is for sure better to keep consistency between all output formats.

**Comment by Damian89** [comment]
Hey guys,
I mentioed this feature also in the past and now saw this PR - what happened? Nobody wanna resolve the conflict? Would be awesome to have the PR in master.

**Review by joohoi — APPROVED** [review]
LGTM!

**Pull request merged**
