### PR TITLE
Update random seed logic

### PR DESCRIPTION
**Pull request by bjhulst**
In GO rand.Intn is not really random at all unless you change the seed value before calling it.

### CODE REVIEW

**Comment by joohoi** [comment]
Thanks for the change. The `rand.seed` is however already called in `job.go`, as it only needs to be seeded once per execution (or job like here). It's much faster that way instead of applying a new seed for every call of the helper function.

This PR could however add a comment pointing that out for all the future readers of the code (myself included). For reference, the seed is set here: https://github.com/ffuf/ffuf/blob/7ffd74d87e15bf7673e323a02da5c4f7582580db/pkg/ffuf/job.go#L93

**Comment by bjhulst** [comment]
Actually I found this issue when running with "calibration-enable" during "several times" and it always gave me the error message with the same random string.... :-)
 
Current code-base gives:
$ ./ffuf -ac -w words.txt -u https://notexisting.com/FUZZ
Error in autocalibration, exiting: Get https://notexisting.com/adminXVlBzgbaiCMRAjWw/: connect: no route to host
$ ./ffuf -ac -w words.txt -u https://notexisting.com/FUZZ
Error in autocalibration, exiting: Get https://notexisting.com/adminXVlBzgbaiCMRAjWw/:  connect: no route to host
$ ./ffuf -ac -w words.txt -u https://notexisting.com/FUZZ
Error in autocalibration, exiting: Get https://notexisting.com/adminXVlBzgbaiCMRAjWw/:  connect: no route to host

Adding the seed as in the PR.
$ vi pkg/ffuf/util.go 
$ go build
$ ./ffuf -ac -w words.txt -u https://notexisting.com/FUZZ
Error in autocalibration, exiting: Get https://notexisting.com/adminPFpLgfKsynySawSo/:  connect: no route to host

**Comment by joohoi** [comment]
Good catch! You are right. 

The autocalibration happens before `job.Start()`. Perhaps a good place to do the random seed initialization would be https://github.com/ffuf/ffuf/blob/7ffd74d87e15bf7673e323a02da5c4f7582580db/main.go#L166 or just `main()`. I think the initialization in `job.Start()` should still stay, as the job runner can be used from external packages as well.

**Comment by bjhulst** [comment]
I did some profiling on the amount of seed updates done when using this code from the PR. The code only calls the "seed update inside the RandomString function" 4 times per execution of the ffuf command. 

I think this current PR code will not harm performance and is cleaner to understand when the rand.Seed + rand.Intn are inside the same function block. :)

**Comment by joohoi** [comment]
I agree that with the current functionality it's not big of an issue. However I think that seeding the random every time a random value is needed is kind of an antipattern, and would have to be changed around whenever the function gets more use. Because of this I think it'd be better to try and find the proper place to do the random seeding.

**Comment by bjhulst** [comment]
How about updating the rand.Seed after https://github.com/ffuf/ffuf/blob/master/pkg/ffuf/job.go#L333  ?

**Comment by bjhulst** [comment]
Is this good to go?

**Comment by bjhulst** [comment]
CHANGELOG.md updated.

**Pull request merged**
