### PR TITLE
Add option for -debug-log.

### PR DESCRIPTION
**Pull request by ccsplit**
Both of these options have to do with the logging surrounding issues
such as #39. Where in that issue the server was returning data after
the connection was closed. Therefore, I added two options one for
completely disabling all of the internal logging functionality aka
sending it to /dev/null. Another for writing the logging information
to a file so it can be retrieved later if need be.

### CODE REVIEW

**Comment by joohoi** [comment]
Thanks for the PR!

I think that it's rarely significant to see these messages, so I would propose the following: 

Using only a single CLI flag: `--debug-log` or so, and defaulting to logging off. Only try to write the logfile if the variable is set.

**Comment by ccsplit** [comment]
@joohoi this has been changed to now only have the `-debug-log <file>` flag and will by default disable logging, it will also disable logging when an error occurs with creating a handle for the specified `<file>`. @aels, are you able to either provide the site you were having the issue with for testing, or build and run my [fork](https://github.com/ccsplit/ffuf) against the site you have to test the functionality? The site I had this issue against is no longer active, therefore, I currently don't have a site having this functionality to test against.

**Comment by aels** [comment]
> @joohoi 
sorry, I'll have no time to test it again, but my query is
`ffuf -w ~/www/tools/alexatop1m.csv -u http://FUZZ/wp-includes/wlwmanifest.xml -of csv -mc 420 -t 8 -timeout 3 -mr "WordPress" -o wordpress2.txt`
where wordlist is from http://s3.amazonaws.com/alexa-static/top-1m.csv.zip, where the only column with domains left.
Hope it will help you.

**Comment by ccsplit** [comment]
Thanks @aels, I tested it and it looks to be working correctly, one of the hosts with this issue is: `interia.pl`, one thing that would be nice, but not sure how difficult it would be, is to change the logger when `-debug-log` is active to add the URL it was testing as the log doesn't help that much.

**Comment by joohoi** [comment]
This looks good and basically ready to merge. Could you add a [changelog](https://github.com/ffuf/ffuf#changelog) entry for this?

**Comment by joohoi** [comment]
Oh, and seems like there's an merge conflict because of some PRs that were just merged.

**Comment by ccsplit** [comment]
Should be resolved, added the flag to the Readme and the changelog as well.

**Pull request merged**
