### PR TITLE
Allow input-shell option

### PR DESCRIPTION
**Pull request by jsgv**
**This is a new pull request that replaces original [pull request](https://github.com/ffuf/ffuf/pull/293)**

* Add flag to set the shell to be used for the the input command

This is in response to issue #141 
Adds support to set the shell to be used with `input-cmd`. Fixes some issues that happen when using the [default shell](https://github.com/ffuf/ffuf/blob/master/pkg/input/const.go#L6) (`/bin/sh`). But still defaults to current shell if not set.

For example:
`echo` does not support `-n` flag in `/bin/sh`

Being able to set `/bin/zsh` or `/bin/bash` would fix the issue.

Usage:
```
ffuf -v \
    -input-shell "/bin/zsh" \
    -input-cmd 'echo -n subscriptions' \
    -input-num 1 -u https://example.com/path1/FUZZ
```

### CODE REVIEW

**Review by joohoi — CHANGES_REQUESTED** [review]
The code looks good. If you could add a short description to `CHANGELOG.md` and yourself to `CONTRIBUTORS.md` (alphabetically sorted), it'd be great!

**Review by jsgv — COMMENTED** [review]
Added updates to markdown files

**Comment by jsgv** [comment]
Anything else? @joohoi

**Review by joohoi — APPROVED** [review]

**Comment by joohoi** [comment]
LGTM!

**Pull request merged**
