### PR TITLE
Add FFUF link to the User-Agent header

### PR DESCRIPTION
**Pull request by shelld3v**
# Description

This is just a small update, so I haven't added my name to `CONTRIBUTORS.md` or add a description to `CHANGELOG.md` yet!

## Additonally

- [x] If this is the first time you are contributing to ffuf, add your name to `CONTRIBUTORS.md`. 
The file should be alphabetically ordered.
- [ ] Add a short description of the fix to `CHANGELOG.md`

Thanks for contributing to ffuf :)

### CODE REVIEW

**Comment by bsysop** [comment]
Hi @shelld3v, you must add your name to contributors anyway =]

I think your idea is good, but probably it will make a bit uglier logs, marketing stats panels, etc.

I think infosec should not disturb other departments and looks we are doing that (headers and plenty other "duplicate-machine" tools)

Something to think about.

**Comment by shelld3v** [comment]
I made this commit because I think that if the server admin sees that log, he will think like: what is the user trying to say to me? What is fuzz? What does he call me a fool? ... Although it's just a tool

**Comment by shelld3v** [comment]
Oh, do you mean that I forgot the give my commit, a NAME?

**Comment by bsysop** [comment]
Yeah, you are absolutely right! But he can search too "Fuff"

Screen Shot 2020-11-24 at 10 35 33

Anyway, i like your idea but i don't like your idea, thanks for try to help and contribute with the community, =]

Let's wait for the boss!

**Comment by bsysop** [comment]
> Oh, do you mean that I forgot the give my commit, a NAME?

I mean, if you did a pull request, you must add your name to contributors.. If is a valuable pull request will be accepted and your name SHOULD be listed there, =]

**Comment by shelld3v** [comment]
NO, I don't see the word `ffuf` in the user agent, just only `Fuzz Faster U Fool v1.0.0.`. If the admin doesn't know it is a name of a tool, he will think that is a sentence

**Comment by bsysop** [comment]
> NO, I don't see the word `ffuf` in the user agent, just only `Fuzz Faster U Fool v1.0.0.`. If the admin doesn't know it is a name of a tool, he will think that is a sentence

If he have that job position, he must almost know how to google, right?

Screen Shot 2020-11-24 at 10 40 16

You had a good idea buddy, just want to show you is not critical, lets see.

**Comment by shelld3v** [comment]
Close btw

**Pull request closed without merging**
