### PR TITLE
chore: implement save output on maxtime reached

### PR DESCRIPTION
**Pull request by dpanic**
# Description

Minor change, saves output if maxtime is reached.

Fixes: #584 

## Additonally
* [x]  If this is the first time you are contributing to ffuf, add your name to `CONTRIBUTORS.md`.
The file should be alphabetically ordered.
* [x]  Add a short description of the fix to `CHANGELOG.md`

### CODE REVIEW

**Comment by dpanic** [comment]
@joohoi did you had time to look at this?

**Comment by dpanic** [comment]
Any updates on this?

**Review by wellenc-lex — APPROVED** [review]
we need this!

**Comment by joohoi** [comment]
Sorry for taking such a long time to get around this PR. I'm a bit confused about it when it comes to the core issue at hand. 

The output should already be saved whenever any of the exit conditions are met. This should happen because whenever `Stop()` is called within the loop that runs the job (and any recursion jobs), is just simply iterated through without actual execution, and the output file save happens directly after before actually quitting.

https://github.com/ffuf/ffuf/blob/master/pkg/ffuf/job.go#L139-L149

If you have encountered a situation where the output file has _not_ been generated, we need to dig into this further as it most likely is a bug somewhere else in the code than a missing attempt to save the file.

**Pull request closed without merging**
