### PR TITLE
Add output to CSV file

### PR DESCRIPTION
**Pull request by seblw**
Hi again,
Another PR this evening :)
Example output content:
```
input,status_code,content_length,content_words
ccc,301,0,1
aaa,301,0,1
```

I'm still not sure about adding timestamp or/and source file to the output.

### CODE REVIEW

**Comment by seblw** [comment]
Yep, good point. Actually I think both approaches could be useful - maybe introducing two output formats like `ecsv` with base64 encoded payload and raw `csv` for some simpler use-cases like when you just bruteforce directories etc. That way the tool can support simple and advanced use cases (assuming that advanced user is able to decode the result hehe :) )

**Comment by joohoi** [comment]
That sounds like a good plan! I'm all for it

**Comment by seblw** [comment]
Good to hear! Will put an update around the evening.

**Comment by seblw** [comment]
Updated.

**Comment by joohoi** [comment]
LGTM! Thanks!

**Pull request merged**
