### PR TITLE
Fix time-based matcher

### PR DESCRIPTION
**Pull request by denandz**
The time-based matcher was being processed as a filter. This PR makes the time-matcher work as expected. The issue was that the `-mt` flag was being sunk into `AddFilter` instead of `AddMatcher`.

Here is a simple test setup, run a test vuln webapp with `docker run -d -p 1234:8000 -it appsecco/dsvw` (there's a blind sqlite injection bug in here)

```
$ wget https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/master/SQL%20Injection/Intruder/Generic_TimeBased.txt
...yoink...  

2022-08-01 19:55:30 (15.3 MB/s) - ‘Generic_TimeBased.txt’ saved [2351/2351]
$ while read -r i; do echo -n "$i" | ~/go/bin/pencode urlencode; echo; done < Generic_TimeBased.txt > urlencoded.txt
$ ~/go/src/github.com/ffuf/ffuf/ffuf -t 1 -u "http://127.0.0.1:1234/?id=§2§"  -mode sniper -w urlencoded.txt -mt ">1000"

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.5.0-dev
________________________________________________

 :: Method           : GET
 :: URL              : http://127.0.0.1:1234/?id=§2§
 :: Wordlist         : FUZZ: urlencoded.txt
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 1
 :: Matcher          : Response time: >1000
________________________________________________

RANDOMBLOB%28500000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 2125ms]
RANDOMBLOB%281000000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 4239ms]
:: Progress: [95/95] :: Job [1/1] :: 1295 req/sec :: Duration: [0:00:06] :: Errors: 0 ::
```

Fixes: #558

### CODE REVIEW

**Comment by denandz** [comment]
And an example using the filter instead, for completeness. This is working as expected and hasn't been modified by this PR.

```
$ ~/go/src/github.com/ffuf/ffuf/ffuf -t 1 -u "http://127.0.0.1:1234/?id=§2§" -mode sniper -w urlencoded.txt -mc all -ft "<1000"

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.5.0-dev
________________________________________________

 :: Method           : GET
 :: URL              : http://127.0.0.1:1234/?id=§2§
 :: Wordlist         : FUZZ: urlencoded.txt
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 1
 :: Matcher          : Response status: all
 :: Filter           : Response time: <1000
________________________________________________

RANDOMBLOB%28500000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 2122ms]
RANDOMBLOB%281000000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 4167ms]
:: Progress: [95/95] :: Job [1/1] :: 1182 req/sec :: Duration: [0:00:06] :: Errors: 0 ::
```

**Comment by D3vil0p3r** [comment]
> And an example using the filter instead, for completeness. This is working as expected and hasn't been modified by this PR.
> 
> ```
> $ ~/go/src/github.com/ffuf/ffuf/ffuf -t 1 -u "http://127.0.0.1:1234/?id=§2§" -mode sniper -w urlencoded.txt -mc all -ft "<1000"
> 
>         /'___\  /'___\           /'___\       
>        /\ \__/ /\ \__/  __  __  /\ \__/       
>        \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
>         \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
>          \ \_\   \ \_\  \ \____/  \ \_\       
>           \/_/    \/_/   \/___/    \/_/       
> 
>        v1.5.0-dev
> ________________________________________________
> 
>  :: Method           : GET
>  :: URL              : http://127.0.0.1:1234/?id=§2§
>  :: Wordlist         : FUZZ: urlencoded.txt
>  :: Follow redirects : false
>  :: Calibration      : false
>  :: Timeout          : 10
>  :: Threads          : 1
>  :: Matcher          : Response status: all
>  :: Filter           : Response time: <1000
> ________________________________________________
> 
> RANDOMBLOB%28500000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 2122ms]
> RANDOMBLOB%281000000000%2F2%29 [Status: 200, Size: 1338, Words: 115, Lines: 11, Duration: 4167ms]
> :: Progress: [95/95] :: Job [1/1] :: 1182 req/sec :: Duration: [0:00:06] :: Errors: 0 ::
> ```

Hello @denandz When this PR will be merged?

**Comment by denandz** [comment]
> Hello @denandz When this PR will be merged?

No idea, sorry. Question for @joohoi

**Comment by joohoi** [comment]
Sorry for the delay, I fixed the merge conflict I caused meanwhile this was in the PR queue. It's merged now :)

**Pull request merged**
