### PR TITLE
Lowered bar for automatching words and sizes from 1 to 0.

### PR DESCRIPTION
**Pull request by fang0654**
This filters out false positives from sites that return 301/302 for every request.

### CODE REVIEW

**Comment by joohoi** [comment]
I think there should be another way to handle this issue. I'll be adding a more elaborate comment to the issue you opened to explain what I'm thinking.

Another thing, to work on and to submit pull requests on Go code repositories, the best approach is probably (using ffuf as an example here):

1) Clone ffuf repository
2) `go get -d github.com/ffuf/ffuf` : this downloads the ffuf code, but doesn't install the binary.
3) cd ~/go/src/github.com/ffuf/ffuf
4) `git remote add my_fork git@github.com:yourusername/ffuf.git`

Then work on the code just like you have been doing, but push the created PR branches to remote `my_fork` :)

**Comment by fang0654** [comment]
Thanks for the info on PRs for Go, that definitely seems a bit cleaner!

**Comment by joohoi** [comment]
Are you interested in changing the PR around in the suggested way in order to eliminate the changes to imports?

**Comment by fang0654** [comment]
Yeah, I'll do a new PR today.On Oct 14, 2019 2:57 AM, Joona Hoikkala <notifications@github.com> wrote:Are you interested in changing the PR around in the suggested way in order to eliminate the changes to imports?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

(null)

**Comment by fang0654** [comment]
I added a new PR #80, so you can close this one.

**Comment by joohoi** [comment]
Closed in favor of #80

**Pull request closed without merging**
